name: Publish Packages

on:
  push:
    branches: [ "main" ]
    #paths:
    #  - 'src/Spoleto.Cryptography.Rsa/**'
    #  - 'LICENSE'
    #  - 'README.md'
      #- 'src/**'
      #- '!src/**.Tests/**'
  pull_request:
    branches: [ main ]

jobs:

  Build-Tests-Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- id: modified
    #  uses: pheel/path-watcher-action@v1
    #  with:
    #      github_token: ${{ secrets.GITHUB_TOKEN }} # no need to set this secret, it is always available!
    #      paths: 'src/Spoleto.Cryptography.Rsa/**'
    #      return_files: false # if true, return an array of the modified paths. defaults to false.
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test with the dotnet CLI
      #if: steps.modified.outputs.modified # run this step if there are changes in the source project
      run: dotnet test --no-restore --logger "trx;LogFileName=test-results.trx"

    - name: Tests report
      uses: dorny/test-reporter@v1.5.0
      if:  ( success() || failure() ) # run this step if there are changes in the source project and even previous step failed
      with:
        name: Test results
        path: '**/test-results.trx'
        reporter: dotnet-trx

    - name: Publish to Nuget
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: src/Spoleto.Cryptography.Rsa/Spoleto.Cryptography.Rsa.csproj
          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: true
